Repository se2024-jpg/Slash, pull requests merged in 2024-11, with the labels that each got.

#1 Update README.md
  README.md
Labels: documentation

#4 Adding Product Comparison Feature - Initial UI
  src/modules/app.py
  src/modules/static/login.html
  src/modules/static/product_comparison.html
  src/modules/static/result.html
  src/modules/static/wishlist.html
Labels: enhancement

#6 Added functionality to search products using voice
  src/modules/app.py
  src/modules/static/login.html
  src/modules/static/result.html
  src/modules/static/script.js
Labels: enhancement

#8 Fix code scanning alert no. 1: Clear-text storage of sensitive information
  install.py
  requirements.txt
Labels: security-issue

#10 Adding database functionality to wishlist
  src/modules/app.py
  src/modules/features.py
  src/modules/models.py
  src/modules/static/wishlist.html
Labels: enhancement, priority-medium

#11 Implement 2FA functionality
  install.py
  src/modules/app.py
  src/modules/static/landing.html
Labels: enhancement, priority-medium

#14 Adding search history functionality
  src/modules/app.py
  src/modules/features.py
  src/modules/models.py
  src/modules/static/login.html
  src/modules/static/product_comparison.html
  src/modules/static/result.html
  src/modules/static/search_history.html
  src/modules/static/wishlist.html
Labels: enhancement, priority-medium

#21 Adding price drop functionality for wishlist items
  src/.DS_Store
  src/modules/.DS_Store
  src/modules/app.py
  src/modules/features.py
  src/modules/models.py
  src/modules/pricedropscraper.py
  src/modules/scraper.py
  src/modules/static/wishlist.html
Labels: enhancement, priority-medium

#23 Fixing issue 22 - Recommendations page error for new users
  src/modules/app.py
Labels: bug, priority-medium

#27 Fix price fetch query for Walmart
  src/modules/scraper.py
Labels: bug, priority-low

#29 UI Refresh
  src/modules/app.py
  src/modules/config.py
  src/modules/features.py
  src/modules/formatter.py
  src/modules/full_version.py
  src/modules/models.py
  src/modules/pricedropscraper.py
  src/modules/scraper.py
  src/modules/static/login.html
  src/modules/static/search_history.html
  src/modules/static/wishlist.html
Labels: enhancement, priority-medium

#38 Fixed encryption issue
  install.py
Labels: bug
